spring:
  jwt:
    secret-key: "asdsasd22asdadas21asdasd2312232asdsa2123saddasadsda"  # Replace with your actual secret key
    access:
      expiration: 3600               # Access token expiration period in seconds
      header: "Authorization"        # Header name for access token
    refresh:
      expiration: 604800             # Refresh token expiration period in seconds
      header: "Refresh-Token"        # Header name for refresh token