spring:
  application:
    name: member-service
  profiles:
    active: db,jwt,oauth
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${username_}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

