
spring:
  jwt:
    secret-key: "asd23he8h31821ghgbsudom23o1gh732siadh2383"  # Replace with your actual secret key
    access:
      expiration: 3600               # Access token expiration period in seconds
      header: "Authorization"        # Header name for access token
    refresh:
      expiration: 604800             # Refresh token expiration period in seconds
      header: "RefreshToken"        # Header name for refresh token